feat: building based on ctrf reporting

diff --git a/apps/simplepmp/Dockerfile b/apps/simplepmp/Dockerfile
--- a/apps/simplepmp/Dockerfile
+++ b/apps/simplepmp/Dockerfile
@@ -12,3 +12,7 @@ RUN npx playwright install
 # Test
 # CMD ["npx", "playwright", "test"]
 RUN npx playwright test
+
+COPY ctrf/ctrf-report.json .
+
+RUN jq -r '.results.summary.failed' ctrf-report.json | grep -q "failed" && { echo "Tests failed. Stopping Docker build."; exit 1; } || echo "Tests passed successfully"
